[package]
name = "md5sumsum"
version = "0.2.0"
authors = ["Koneko76 <clementdelaunay3002@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
